<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>scopeName</key>
		<string>text.log</string>

		<key>fileTypes</key>
		<array>
			<string>log</string>
			<string>log.1</string>
			<string>log.2</string>
			<string>log.3</string>
			<string>log.4</string>
			<string>log.5</string>
		</array>

		<key>name</key>
		<string>Log file</string>

		<key>patterns</key>
		<array>
		
			<!-- Log levels -->
			<dict>
				<key>match</key>
				<string>\b(DEBUG|TRACE)\b</string>
				<key>name</key>
				<string>debug-token</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(HINT|INFO|INFORMATION)\b</string>
				<key>name</key>

				<string>info-token</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(WARNING|WARN)\b</string>
				<key>name</key>
				<string>warn-token</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(ERROR|FAILURE|FAIL|FATAL)\b</string>
				<key>name</key>
				<string>error-token</string>
			</dict>

			<!-- Dates -->
			<dict>
				<key>match</key>
				<string>\d{4}-\d{2}-\d{2}( \d{2}:\d{2}(:\d{2}(,\d{3})?)?)?</string>
				<key>name</key>
				<string>comment</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\d{2}:\d{2}(:\d{2}([\.,]\d{3})?)?</string>
				<key>name</key>
				<string>comment</string>
			</dict>

			<!-- Numbers -->
			<dict>
				<key>match</key>
				<string>\b(0?[xX][0-9a-fA-F]+)\b</string>
				<key>name</key>
				<string>number.hex</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b([0-9a-fA-F]{2})\b</string>
				<key>name</key>
				<string>number</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b([0-9]+)\b</string>
				<key>name</key>
				<string>number</string>
			</dict>
			
			<!-- Constants -->
			<dict>
				<key>match</key>
				<string>\b(true|false|null|TRUE|FALSE|NULL)\b</string>
				<key>name</key>
				<string>constant</string>
			</dict>

			<!-- String constants -->
			<dict>
				<key>match</key>
				<string>"[^"]*"</string>
				<key>name</key>
				<string>string</string>
			</dict>
	
			<dict>
				<key>match</key>
				<string>'[^']*'</string>
				<key>name</key>
				<string>string</string>
			</dict>

			<!-- Exception type names -->
			<dict>
				<key>match</key>
				<string>\b([a-zA-Z.]*Exception)\b</string>
				<key>name</key>
				<string>error-token</string>
			</dict>
			
			<!-- Colorize rows of exception call stacks -->
			<dict>
				<key>begin</key>
				<string>^[\t ]*at</string>
				<key>end</key>
				<string>$</string>
				<key>name</key>
				<!-- <string>keyword</string> -->
				<string>identifier.method</string>
			</dict>
			
		</array>
		
		<key>uuid</key>
		<string>376f0c9e-a4a5-11e5-bf7f-feff819cdc9f</string>
	</dict>
</plist>